# Generated by Django 6.0.1 on 2026-01-26 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear_term'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teachingassignment',
            name='unique_teacher_class_subject',
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academics.term'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom', 'subject', 'term'), name='unique_teaching_assignment'),
        ),
    ]
