# Generated by Django 6.0.1 on 2026-01-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7'), ('G8', 'Grade 8'), ('G9', 'Grade 9'), ('F1', 'Form 1'), ('F2', 'Form 2'), ('F3', 'Form 3'), ('F4', 'Form 4'), ('F5', 'Form 5'), ('F6', 'Form 6')], max_length=2)),
                ('stream', models.CharField(blank=True, max_length=10)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('level', 'stream', 'year'), name='unique_classroom_level_stream_year')],
            },
        ),
    ]
